---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: python-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - image: python-app-example:1
          imagePullPolicy: Never
          name: python-app
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler