---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-app
  name: python-app
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-app
  type: NodePort