---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-http-server
  name: python-http-server
  namespace: python-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-http-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-http-server
    spec:
      containers:
        - name: python-http-server
          image: michaltrmac/onpk-python-app:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DOCKER_IMAGE
              value: michaltrmac/onpk-python-app:1.0.0
          ports:
            - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
